name: Run iOS Tests on macOS Simulator

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: false
        default: 'main'

jobs:
  run-ios-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install xcuitest
          appium driver list

      - name: Start Appium server
        run: |
          appium 

      - name: Start iOS Simulator
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          SIMULATOR_ID=$(xcrun simctl list devices available | grep "iPhone 15" | awk -F '[()]' '{print $2}' | head -n 1)
          xcrun simctl boot "$SIMULATOR_ID"

      - name: Run iOS tests
        run: |
          
          robot -d Results Tests/

      - name: Upload iOS test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-test-results
          path: Results/iOS

      - name: Upload Appium logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-logs
          path: appium.log